// Mocks generated by Mockito 5.4.6 from annotations
// in tradie/test/mocks/tradie_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:tradie/core/network/api_result.dart' as _i4;
import 'package:tradie/features/fetch_tradies/models/tradie_model.dart' as _i7;
import 'package:tradie/features/fetch_tradies/models/tradie_request.dart'
    as _i5;
import 'package:tradie/features/fetch_tradies/repositories/tradie_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [TradieRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTradieRepository extends _i1.Mock implements _i2.TradieRepository {
  MockTradieRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<List<_i5.TradieRequest>>> fetchJobs({
    String? status,
    int? page = 1,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchJobs, [], {#status: status, #page: page}),
            returnValue:
                _i3.Future<_i4.ApiResult<List<_i5.TradieRequest>>>.value(
                  _i6.dummyValue<_i4.ApiResult<List<_i5.TradieRequest>>>(
                    this,
                    Invocation.method(#fetchJobs, [], {
                      #status: status,
                      #page: page,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.ApiResult<List<_i5.TradieRequest>>>);

  @override
  _i3.Future<_i4.ApiResult<_i5.TradieRequest>> fetchJobDetail(int? jobId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchJobDetail, [jobId]),
            returnValue: _i3.Future<_i4.ApiResult<_i5.TradieRequest>>.value(
              _i6.dummyValue<_i4.ApiResult<_i5.TradieRequest>>(
                this,
                Invocation.method(#fetchJobDetail, [jobId]),
              ),
            ),
          )
          as _i3.Future<_i4.ApiResult<_i5.TradieRequest>>);

  @override
  _i3.Future<_i4.ApiResult<List<_i7.TradieModel>>> fetchRecommendedTradies(
    int? jobId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchRecommendedTradies, [jobId]),
            returnValue: _i3.Future<_i4.ApiResult<List<_i7.TradieModel>>>.value(
              _i6.dummyValue<_i4.ApiResult<List<_i7.TradieModel>>>(
                this,
                Invocation.method(#fetchRecommendedTradies, [jobId]),
              ),
            ),
          )
          as _i3.Future<_i4.ApiResult<List<_i7.TradieModel>>>);
}
