// Mocks generated by Mockito 5.4.5 from annotations
// in homeowner/test/auth/viewmodels/auth_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:homeowner/core/network/api_result.dart' as _i4;
import 'package:homeowner/features/auth/models/auth_models.dart' as _i5;
import 'package:homeowner/features/auth/repositories/auth_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i2.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<_i5.AuthResponse>> login(
    _i5.LoginRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#login, [request]),
            returnValue: _i3.Future<_i4.ApiResult<_i5.AuthResponse>>.value(
              _i6.dummyValue<_i4.ApiResult<_i5.AuthResponse>>(
                this,
                Invocation.method(#login, [request]),
              ),
            ),
          )
          as _i3.Future<_i4.ApiResult<_i5.AuthResponse>>);

  @override
  _i3.Future<_i4.ApiResult<_i5.AuthResponse>> register(
    _i5.RegisterRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#register, [request]),
            returnValue: _i3.Future<_i4.ApiResult<_i5.AuthResponse>>.value(
              _i6.dummyValue<_i4.ApiResult<_i5.AuthResponse>>(
                this,
                Invocation.method(#register, [request]),
              ),
            ),
          )
          as _i3.Future<_i4.ApiResult<_i5.AuthResponse>>);

  @override
  _i3.Future<_i4.ApiResult<bool>> verifyEmail(String? email, String? token) =>
      (super.noSuchMethod(
            Invocation.method(#verifyEmail, [email, token]),
            returnValue: _i3.Future<_i4.ApiResult<bool>>.value(
              _i6.dummyValue<_i4.ApiResult<bool>>(
                this,
                Invocation.method(#verifyEmail, [email, token]),
              ),
            ),
          )
          as _i3.Future<_i4.ApiResult<bool>>);

  @override
  _i3.Future<_i4.ApiResult<bool>> resendVerification(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#resendVerification, [email]),
            returnValue: _i3.Future<_i4.ApiResult<bool>>.value(
              _i6.dummyValue<_i4.ApiResult<bool>>(
                this,
                Invocation.method(#resendVerification, [email]),
              ),
            ),
          )
          as _i3.Future<_i4.ApiResult<bool>>);

  @override
  _i3.Future<_i4.ApiResult<bool>> requestPasswordReset(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#requestPasswordReset, [email]),
            returnValue: _i3.Future<_i4.ApiResult<bool>>.value(
              _i6.dummyValue<_i4.ApiResult<bool>>(
                this,
                Invocation.method(#requestPasswordReset, [email]),
              ),
            ),
          )
          as _i3.Future<_i4.ApiResult<bool>>);

  @override
  _i3.Future<_i4.ApiResult<bool>> verifyResetPasswordOtp(
    String? email,
    String? otp,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyResetPasswordOtp, [email, otp]),
            returnValue: _i3.Future<_i4.ApiResult<bool>>.value(
              _i6.dummyValue<_i4.ApiResult<bool>>(
                this,
                Invocation.method(#verifyResetPasswordOtp, [email, otp]),
              ),
            ),
          )
          as _i3.Future<_i4.ApiResult<bool>>);

  @override
  _i3.Future<_i4.ApiResult<bool>> resetPassword({
    required String? email,
    required String? newPassword,
    required String? confirmNewPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [], {
              #email: email,
              #newPassword: newPassword,
              #confirmNewPassword: confirmNewPassword,
            }),
            returnValue: _i3.Future<_i4.ApiResult<bool>>.value(
              _i6.dummyValue<_i4.ApiResult<bool>>(
                this,
                Invocation.method(#resetPassword, [], {
                  #email: email,
                  #newPassword: newPassword,
                  #confirmNewPassword: confirmNewPassword,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.ApiResult<bool>>);

  @override
  _i3.Future<_i4.ApiResult<void>> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i3.Future<_i4.ApiResult<void>>.value(
              _i6.dummyValue<_i4.ApiResult<void>>(
                this,
                Invocation.method(#logout, []),
              ),
            ),
          )
          as _i3.Future<_i4.ApiResult<void>>);

  @override
  _i3.Future<bool> isLoggedIn() =>
      (super.noSuchMethod(
            Invocation.method(#isLoggedIn, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}
